version: '3.6'
services:
  app:
    container_name: java-utility
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    tty: true
    depends_on:
      - mariadb
      - redis
    networks:
      - spring-cloud-network
  redis:
    container_name: redis
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    restart: always
    networks:
      - spring-cloud-network
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/initdb.d:/docker-entrypoint-initdb.d
      - ./mariadb/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: local_mariadb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge