# Settings Server
server:
  port: 8080

# mybatis config
mybatis:
  configuration:
    map-underscore-to-camel-case: true

# Settings Spring
spring:
  # Database
  datasource:
    url: jdbc:mariadb://mariadb:3306/local_mariadb
    username: admin
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
    # Avoid Override
    main:
      allow-bean-definition-overriding: true
  # hibernate
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  # Logging Color
  output:
    ansi:
      enabled: always
  # Jackson
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  # Redis
  redis:
    host: redis
    port: 6379
