openapi: 3.0.0
info:
  title: Auth API
  description: Authentication API
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1/
    description: authentication servers

paths:
  /auth:
    post:
      summary: Generate Token
      operationId: getToken
      tags:
        - AuthApi
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        200:
          description: Generate Token Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        400:
          description: Invalid Request Parameter
          content:
            application/json:
              schema:
                title: AccessDeniedException
                $ref: ../schemas/common/FailureResponse.yml#/components/schemas/ApiErrorResponse
        403:
          description: Forbidden, An Match Account name or Password
          content:
            application/json:
              schema:
                title: AccessDeniedException
                $ref: ../schemas/common/FailureResponse.yml#/components/schemas/ApiErrorResponse
  /auth/refresh:
    post:
      summary: Refresh Token
      operationId: refreshTokenToken
      tags:
        - AuthApi
      parameters:
      - in: header
        name: Authentication
        description: JWT Token, Prefix Bearer
        example: Bearer XXXXXXX-XXXXXXXX-XXXXXXXX
        required: true
        schema:
          type: string
      responses:
        200:
          description: Refresh Token Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        400:
          description: Token is Null or Empty.
          content:
            application/json:
              schema:
                title: AccessDeniedException
                $ref: ../schemas/common/FailureResponse.yml#/components/schemas/ApiErrorResponse
        403:
          description: Forbidden, Incorrect token
          content:
            application/json:
              schema:
                title: AccessDeniedException
                $ref: ../schemas/common/FailureResponse.yml#/components/schemas/ApiErrorResponse

components:
  schemas:
    AuthRequest:
      $ref: ../schemas/Auth.yml#/components/schemas/Auth
    TokenResponse:
      $ref: ../schemas/Token.yml#/components/schemas/Token